/***********************************************************************/
/*                                                                     */
/*  FILE        :main.c                                                */
/*  DATE        :Sat, Dec 21, 2019                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/36064                                              */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
#include "iodefine.h"
#include "led.h"
#include "sw.h"
#include "timer.h"
#include "lsen.h"
/**************************************
 * 内部プロトタイプ宣言
 **************************************/
void main_init(void);

/**************************************
 * 概要：エントリーポイント
 **************************************/

void main(void){

	unsigned short sen1, sen2;
	main_init();

	while(1){
		/* センサー1、2の値を取得する */
		Lsen_getSensor(&sen1, &sen2);

		if (sen1 >= 512){
			/* オレンジLEDを点灯する */
			Led_setLight(D_LED_KIND_ORANGE, D_LED_LIGHT_ON);
		}else{
			/* オレンジLEDを消灯する */
			Led_setLight(D_LED_KIND_ORANGE, D_LED_LIGHT_OFF);
		}

		if (sen2 >= 512){
			/* グリーンLEDを点灯する */
			Led_setLight(D_LED_KIND_GREEN, D_LED_LIGHT_ON);
		}else{
			/* グリーンLEDを消灯する */
			Led_setLight(D_LED_KIND_GREEN, D_LED_LIGHT_OFF);
		}
	}
}

/*
 * @brief システム初期化処理
 * @param (void)
 * @return (void)
 */
void main_init(void){
	/*************************************
	 * ウォッチドッグタイマの停止（消さないこと）
	 *************************************/
	WDT.TCSRWD.BYTE = 0x92;
	WDT.TCSRWD.BYTE = 0x92;

	/*************************************
	 * PCRの設定(PCRは書き込み専用レジスタ)
	 *************************************/
	IO.PCR6 = 0x11; //P60, P64を出力
	IO.PCR7 = 0x00; //P74を入力

	/*************************************
	 * モジュールの初期化(各モジュールの初期化を実施)
	 *************************************/
	 Led_init();
	 Sw_init();
	 Timer_init();
	 Lsen_init();
}
